name: CI

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Lint client
        working-directory: ./client
        run: |
          npm ci
          npm run lint
      - name: Lint server
        working-directory: ./server
        run: |
          npm ci
          npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Test client
        working-directory: ./client
        run: |
          npm ci
          npm test
      - name: Test server
        working-directory: ./server
        run: |
          npm ci
          npm test
