name: CI

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '16'
          - name: Lint client
            run: bash -c 'cd client && npm install && npm run lint'
          - name: Lint server
            run: bash -c 'cd server && npm install && npm run lint'
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Test client
        run: bash -c 'cd client && npm install && npm test'
      - name: Test server
        run: bash -c 'cd server && npm install && npm test'
