name: CI

on:
  pull_request:
    branches: [main, template]
  push:
    branches: [main, template]

jobs:
  lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '16'
          - name: Lint client
            run: cd client && npm ci && npm run lint
          - name: Lint server
            run: cd ../server && npm ci && npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Test client
        run: cd client && npm ci && npm test
        env:
          CI: true
      - name: Test server
        run: cd ../server && npm ci && npm test
        env:
          CI: true
